# Generated by Django 4.2.6 on 2023-10-18 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job.category'),
        ),
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(null=True, upload_to='jobs/'),
        ),
    ]
